sudo: false
language: node_js

node_js:
  - "8"
  - "10"

env:
  - SERVERLESS_VERSION=latest

install:
  - travis_retry yarn
  - yarn global add serverless@SERVERLESS_VERSION

script:
  - yarn lint
  - yarn test
  - yarn integration

after_success:
  - yarn coverage