name: Release

on:
  push:
    branches: [master]

jobs:
    
  release:
    runs-on: ubuntu-latest
    needs: status-check
    steps:
      - uses: actions/checkout@v1
      - name: Release
        uses: brpaz/action-semantic-release@v1
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
