name: Release
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Skip based on commit message
      uses: veggiemonk/skip-commit@1.0.0
      env:
        COMMIT_FILTER: skip ci
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Release new version
      run: |
        yarn --frozen-lockfile
        yarn release
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
