name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        serverless-version: [latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install serverless
      run: yarn global add serverless@${{ matrix.serverless-version }}
    - name: Lint and test
      run: |
        yarn lint
        yarn test
        yarn integration
        yarn coverage
      env:
        CI: true
